// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: buttonsss

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Panel1 = lv_obj_create(ui_Screen1);
lv_obj_remove_style_all(ui_Panel1);
lv_obj_set_width( ui_Panel1, 205);
lv_obj_set_height( ui_Panel1, 205);
lv_obj_set_x( ui_Panel1, -122 );
lv_obj_set_y( ui_Panel1, -105 );
lv_obj_set_align( ui_Panel1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel1,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_Panel1, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_SPACE_BETWEEN);
lv_obj_clear_flag( ui_Panel1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_panel1_1 = lv_btn_create(ui_Panel1);
lv_obj_set_width( ui_panel1_1, 100);
lv_obj_set_height( ui_panel1_1, 100);
lv_obj_set_x( ui_panel1_1, -120 );
lv_obj_set_y( ui_panel1_1, -142 );
lv_obj_set_align( ui_panel1_1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_panel1_1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_panel1_1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_panel1_1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_panel1_1, lv_color_hex(0xC7A881), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_panel1_1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_panel1_1_name2 = lv_label_create(ui_panel1_1);
lv_obj_set_width( ui_panel1_1_name2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_panel1_1_name2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_panel1_1_name2, 0 );
lv_obj_set_y( ui_panel1_1_name2, 10 );
lv_obj_set_align( ui_panel1_1_name2, LV_ALIGN_CENTER );
lv_label_set_text(ui_panel1_1_name2,"淋浴灯");
lv_obj_set_style_text_color(ui_panel1_1_name2, lv_color_hex(0xF9C584), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_panel1_1_name2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_panel1_1_name2, &ui_font_ooMode, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_panel1_1_polit2 = lv_label_create(ui_panel1_1);
lv_obj_set_width( ui_panel1_1_polit2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_panel1_1_polit2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_panel1_1_polit2, 0 );
lv_obj_set_y( ui_panel1_1_polit2, -36 );
lv_obj_set_align( ui_panel1_1_polit2, LV_ALIGN_CENTER );
lv_label_set_text(ui_panel1_1_polit2,"....");
lv_obj_set_style_text_color(ui_panel1_1_polit2, lv_color_hex(0xCACACA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_panel1_1_polit2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_panel1_1_polit2, &ui_font_ooMode, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_panel1_2 = lv_btn_create(ui_Panel1);
lv_obj_set_width( ui_panel1_2, 100);
lv_obj_set_height( ui_panel1_2, 100);
lv_obj_set_x( ui_panel1_2, 100 );
lv_obj_set_y( ui_panel1_2, -145 );
lv_obj_set_align( ui_panel1_2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_panel1_2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_panel1_2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_panel1_2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_panel1_2, lv_color_hex(0xC7A881), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_panel1_2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_panel1_2_name2 = lv_label_create(ui_panel1_2);
lv_obj_set_width( ui_panel1_2_name2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_panel1_2_name2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_panel1_2_name2, 0 );
lv_obj_set_y( ui_panel1_2_name2, 10 );
lv_obj_set_align( ui_panel1_2_name2, LV_ALIGN_CENTER );
lv_label_set_text(ui_panel1_2_name2,"镜前灯");
lv_obj_set_style_text_color(ui_panel1_2_name2, lv_color_hex(0xF9C584), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_panel1_2_name2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_panel1_2_name2, &ui_font_ooMode, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_panel1_2_polit2 = lv_label_create(ui_panel1_2);
lv_obj_set_width( ui_panel1_2_polit2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_panel1_2_polit2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_panel1_2_polit2, 0 );
lv_obj_set_y( ui_panel1_2_polit2, -36 );
lv_obj_set_align( ui_panel1_2_polit2, LV_ALIGN_CENTER );
lv_label_set_text(ui_panel1_2_polit2,"....");
lv_obj_set_style_text_color(ui_panel1_2_polit2, lv_color_hex(0xCACACA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_panel1_2_polit2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_panel1_2_polit2, &ui_font_ooMode, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_panel1_3 = lv_btn_create(ui_Panel1);
lv_obj_set_width( ui_panel1_3, 100);
lv_obj_set_height( ui_panel1_3, 100);
lv_obj_set_x( ui_panel1_3, -132 );
lv_obj_set_y( ui_panel1_3, 70 );
lv_obj_set_align( ui_panel1_3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_panel1_3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_panel1_3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_panel1_3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_panel1_3, lv_color_hex(0xC7A881), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_panel1_3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_panel1_3_name2 = lv_label_create(ui_panel1_3);
lv_obj_set_width( ui_panel1_3_name2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_panel1_3_name2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_panel1_3_name2, 0 );
lv_obj_set_y( ui_panel1_3_name2, 10 );
lv_obj_set_align( ui_panel1_3_name2, LV_ALIGN_CENTER );
lv_label_set_text(ui_panel1_3_name2,"廊灯");
lv_obj_set_style_text_color(ui_panel1_3_name2, lv_color_hex(0xF9C584), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_panel1_3_name2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_panel1_3_name2, &ui_font_ooMode, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_panel1_3_polit2 = lv_label_create(ui_panel1_3);
lv_obj_set_width( ui_panel1_3_polit2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_panel1_3_polit2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_panel1_3_polit2, 0 );
lv_obj_set_y( ui_panel1_3_polit2, -36 );
lv_obj_set_align( ui_panel1_3_polit2, LV_ALIGN_CENTER );
lv_label_set_text(ui_panel1_3_polit2,"....");
lv_obj_set_style_text_color(ui_panel1_3_polit2, lv_color_hex(0xCACACA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_panel1_3_polit2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_panel1_3_polit2, &ui_font_ooMode, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_panel1_4 = lv_btn_create(ui_Panel1);
lv_obj_set_width( ui_panel1_4, 100);
lv_obj_set_height( ui_panel1_4, 100);
lv_obj_set_x( ui_panel1_4, 68 );
lv_obj_set_y( ui_panel1_4, 59 );
lv_obj_set_align( ui_panel1_4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_panel1_4, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_panel1_4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_panel1_4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_panel1_4, lv_color_hex(0xC7A881), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_panel1_4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_panel1_4_name2 = lv_label_create(ui_panel1_4);
lv_obj_set_width( ui_panel1_4_name2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_panel1_4_name2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_panel1_4_name2, 0 );
lv_obj_set_y( ui_panel1_4_name2, 10 );
lv_obj_set_align( ui_panel1_4_name2, LV_ALIGN_CENTER );
lv_label_set_text(ui_panel1_4_name2,"排气扇");
lv_obj_set_style_text_color(ui_panel1_4_name2, lv_color_hex(0xF9C584), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_panel1_4_name2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_panel1_4_name2, &ui_font_ooMode, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_panel1_4_polit2 = lv_label_create(ui_panel1_4);
lv_obj_set_width( ui_panel1_4_polit2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_panel1_4_polit2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_panel1_4_polit2, 0 );
lv_obj_set_y( ui_panel1_4_polit2, -36 );
lv_obj_set_align( ui_panel1_4_polit2, LV_ALIGN_CENTER );
lv_label_set_text(ui_panel1_4_polit2,"....");
lv_obj_set_style_text_color(ui_panel1_4_polit2, lv_color_hex(0xCACACA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_panel1_4_polit2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_panel1_4_polit2, &ui_font_ooMode, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel2 = lv_obj_create(ui_Screen1);
lv_obj_remove_style_all(ui_Panel2);
lv_obj_set_width( ui_Panel2, 205);
lv_obj_set_height( ui_Panel2, 205);
lv_obj_set_x( ui_Panel2, 119 );
lv_obj_set_y( ui_Panel2, -103 );
lv_obj_set_align( ui_Panel2, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel2,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_Panel2, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_SPACE_BETWEEN);
lv_obj_clear_flag( ui_Panel2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel2, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_panel1_5 = lv_btn_create(ui_Panel2);
lv_obj_set_width( ui_panel1_5, 100);
lv_obj_set_height( ui_panel1_5, 100);
lv_obj_set_x( ui_panel1_5, -120 );
lv_obj_set_y( ui_panel1_5, -142 );
lv_obj_set_align( ui_panel1_5, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_panel1_5, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_panel1_5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_panel1_5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_panel1_5, lv_color_hex(0xC7A881), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_panel1_5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_panel1_1_name1 = lv_label_create(ui_panel1_5);
lv_obj_set_width( ui_panel1_1_name1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_panel1_1_name1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_panel1_1_name1, 0 );
lv_obj_set_y( ui_panel1_1_name1, 10 );
lv_obj_set_align( ui_panel1_1_name1, LV_ALIGN_CENTER );
lv_label_set_text(ui_panel1_1_name1,"影音模式");
lv_obj_set_style_text_color(ui_panel1_1_name1, lv_color_hex(0xF9C584), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_panel1_1_name1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_panel1_1_name1, &ui_font_ooMode, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_panel1_1_polit1 = lv_label_create(ui_panel1_5);
lv_obj_set_width( ui_panel1_1_polit1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_panel1_1_polit1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_panel1_1_polit1, 0 );
lv_obj_set_y( ui_panel1_1_polit1, -36 );
lv_obj_set_align( ui_panel1_1_polit1, LV_ALIGN_CENTER );
lv_label_set_text(ui_panel1_1_polit1,"....");
lv_obj_set_style_text_color(ui_panel1_1_polit1, lv_color_hex(0xCACACA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_panel1_1_polit1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_panel1_1_polit1, &ui_font_ooMode, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_panel1_6 = lv_btn_create(ui_Panel2);
lv_obj_set_width( ui_panel1_6, 100);
lv_obj_set_height( ui_panel1_6, 100);
lv_obj_set_x( ui_panel1_6, 100 );
lv_obj_set_y( ui_panel1_6, -145 );
lv_obj_set_align( ui_panel1_6, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_panel1_6, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_panel1_6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_panel1_6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_panel1_6, lv_color_hex(0xC7A881), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_panel1_6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_panel1_2_name1 = lv_label_create(ui_panel1_6);
lv_obj_set_width( ui_panel1_2_name1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_panel1_2_name1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_panel1_2_name1, 0 );
lv_obj_set_y( ui_panel1_2_name1, 10 );
lv_obj_set_align( ui_panel1_2_name1, LV_ALIGN_CENTER );
lv_label_set_text(ui_panel1_2_name1,"明亮模式");
lv_obj_set_style_text_color(ui_panel1_2_name1, lv_color_hex(0xF9C584), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_panel1_2_name1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_panel1_2_name1, &ui_font_ooMode, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_panel1_2_polit1 = lv_label_create(ui_panel1_6);
lv_obj_set_width( ui_panel1_2_polit1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_panel1_2_polit1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_panel1_2_polit1, 0 );
lv_obj_set_y( ui_panel1_2_polit1, -36 );
lv_obj_set_align( ui_panel1_2_polit1, LV_ALIGN_CENTER );
lv_label_set_text(ui_panel1_2_polit1,"....");
lv_obj_set_style_text_color(ui_panel1_2_polit1, lv_color_hex(0xCACACA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_panel1_2_polit1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_panel1_2_polit1, &ui_font_ooMode, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_panel1_7 = lv_btn_create(ui_Panel2);
lv_obj_set_width( ui_panel1_7, 100);
lv_obj_set_height( ui_panel1_7, 100);
lv_obj_set_x( ui_panel1_7, -132 );
lv_obj_set_y( ui_panel1_7, 70 );
lv_obj_set_align( ui_panel1_7, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_panel1_7, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_panel1_7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_panel1_7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_panel1_7, lv_color_hex(0xC7A881), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_panel1_7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_panel1_3_name1 = lv_label_create(ui_panel1_7);
lv_obj_set_width( ui_panel1_3_name1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_panel1_3_name1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_panel1_3_name1, 0 );
lv_obj_set_y( ui_panel1_3_name1, 10 );
lv_obj_set_align( ui_panel1_3_name1, LV_ALIGN_CENTER );
lv_label_set_text(ui_panel1_3_name1,"睡眠模式");
lv_obj_set_style_text_color(ui_panel1_3_name1, lv_color_hex(0xF9C584), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_panel1_3_name1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_panel1_3_name1, &ui_font_ooMode, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_panel1_3_polit1 = lv_label_create(ui_panel1_7);
lv_obj_set_width( ui_panel1_3_polit1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_panel1_3_polit1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_panel1_3_polit1, 0 );
lv_obj_set_y( ui_panel1_3_polit1, -36 );
lv_obj_set_align( ui_panel1_3_polit1, LV_ALIGN_CENTER );
lv_label_set_text(ui_panel1_3_polit1,"....");
lv_obj_set_style_text_color(ui_panel1_3_polit1, lv_color_hex(0xCACACA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_panel1_3_polit1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_panel1_3_polit1, &ui_font_ooMode, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_panel1_8 = lv_btn_create(ui_Panel2);
lv_obj_set_width( ui_panel1_8, 100);
lv_obj_set_height( ui_panel1_8, 100);
lv_obj_set_x( ui_panel1_8, 68 );
lv_obj_set_y( ui_panel1_8, 59 );
lv_obj_set_align( ui_panel1_8, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_panel1_8, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_panel1_8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_panel1_8, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_panel1_8, lv_color_hex(0xC7A881), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_panel1_8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_panel1_4_name1 = lv_label_create(ui_panel1_8);
lv_obj_set_width( ui_panel1_4_name1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_panel1_4_name1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_panel1_4_name1, 0 );
lv_obj_set_y( ui_panel1_4_name1, 10 );
lv_obj_set_align( ui_panel1_4_name1, LV_ALIGN_CENTER );
lv_label_set_text(ui_panel1_4_name1,"阅读模式");
lv_obj_set_style_text_color(ui_panel1_4_name1, lv_color_hex(0xF9C584), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_panel1_4_name1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_panel1_4_name1, &ui_font_ooMode, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_panel1_4_polit1 = lv_label_create(ui_panel1_8);
lv_obj_set_width( ui_panel1_4_polit1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_panel1_4_polit1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_panel1_4_polit1, 0 );
lv_obj_set_y( ui_panel1_4_polit1, -36 );
lv_obj_set_align( ui_panel1_4_polit1, LV_ALIGN_CENTER );
lv_label_set_text(ui_panel1_4_polit1,"....");
lv_obj_set_style_text_color(ui_panel1_4_polit1, lv_color_hex(0xCACACA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_panel1_4_polit1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_panel1_4_polit1, &ui_font_ooMode, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel3 = lv_obj_create(ui_Screen1);
lv_obj_remove_style_all(ui_Panel3);
lv_obj_set_width( ui_Panel3, 205);
lv_obj_set_height( ui_Panel3, 205);
lv_obj_set_x( ui_Panel3, -120 );
lv_obj_set_y( ui_Panel3, 135 );
lv_obj_set_align( ui_Panel3, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel3,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_Panel3, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_SPACE_BETWEEN);
lv_obj_clear_flag( ui_Panel3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel3, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_panel1_9 = lv_btn_create(ui_Panel3);
lv_obj_set_width( ui_panel1_9, 100);
lv_obj_set_height( ui_panel1_9, 100);
lv_obj_set_x( ui_panel1_9, -120 );
lv_obj_set_y( ui_panel1_9, -142 );
lv_obj_set_align( ui_panel1_9, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_panel1_9, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_panel1_9, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_panel1_9, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_panel1_9, lv_color_hex(0xC7A881), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_panel1_9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_panel1_1_name3 = lv_label_create(ui_panel1_9);
lv_obj_set_width( ui_panel1_1_name3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_panel1_1_name3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_panel1_1_name3, 0 );
lv_obj_set_y( ui_panel1_1_name3, 10 );
lv_obj_set_align( ui_panel1_1_name3, LV_ALIGN_CENTER );
lv_label_set_text(ui_panel1_1_name3,"窗纱开");
lv_obj_set_style_text_color(ui_panel1_1_name3, lv_color_hex(0xF9C584), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_panel1_1_name3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_panel1_1_name3, &ui_font_ooMode, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_panel1_1_polit3 = lv_label_create(ui_panel1_9);
lv_obj_set_width( ui_panel1_1_polit3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_panel1_1_polit3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_panel1_1_polit3, 0 );
lv_obj_set_y( ui_panel1_1_polit3, -36 );
lv_obj_set_align( ui_panel1_1_polit3, LV_ALIGN_CENTER );
lv_label_set_text(ui_panel1_1_polit3,"....");
lv_obj_set_style_text_color(ui_panel1_1_polit3, lv_color_hex(0xCACACA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_panel1_1_polit3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_panel1_1_polit3, &ui_font_ooMode, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_panel1_10 = lv_btn_create(ui_Panel3);
lv_obj_set_width( ui_panel1_10, 100);
lv_obj_set_height( ui_panel1_10, 100);
lv_obj_set_x( ui_panel1_10, 100 );
lv_obj_set_y( ui_panel1_10, -145 );
lv_obj_set_align( ui_panel1_10, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_panel1_10, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_panel1_10, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_panel1_10, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_panel1_10, lv_color_hex(0xC7A881), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_panel1_10, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_panel1_2_name3 = lv_label_create(ui_panel1_10);
lv_obj_set_width( ui_panel1_2_name3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_panel1_2_name3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_panel1_2_name3, 0 );
lv_obj_set_y( ui_panel1_2_name3, 10 );
lv_obj_set_align( ui_panel1_2_name3, LV_ALIGN_CENTER );
lv_label_set_text(ui_panel1_2_name3,"窗帘开");
lv_obj_set_style_text_color(ui_panel1_2_name3, lv_color_hex(0xF9C584), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_panel1_2_name3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_panel1_2_name3, &ui_font_ooMode, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_panel1_2_polit3 = lv_label_create(ui_panel1_10);
lv_obj_set_width( ui_panel1_2_polit3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_panel1_2_polit3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_panel1_2_polit3, 0 );
lv_obj_set_y( ui_panel1_2_polit3, -36 );
lv_obj_set_align( ui_panel1_2_polit3, LV_ALIGN_CENTER );
lv_label_set_text(ui_panel1_2_polit3,"....");
lv_obj_set_style_text_color(ui_panel1_2_polit3, lv_color_hex(0xCACACA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_panel1_2_polit3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_panel1_2_polit3, &ui_font_ooMode, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_panel1_11 = lv_btn_create(ui_Panel3);
lv_obj_set_width( ui_panel1_11, 100);
lv_obj_set_height( ui_panel1_11, 100);
lv_obj_set_x( ui_panel1_11, -132 );
lv_obj_set_y( ui_panel1_11, 70 );
lv_obj_set_align( ui_panel1_11, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_panel1_11, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_panel1_11, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_panel1_11, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_panel1_11, lv_color_hex(0xC7A881), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_panel1_11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_panel1_3_name3 = lv_label_create(ui_panel1_11);
lv_obj_set_width( ui_panel1_3_name3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_panel1_3_name3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_panel1_3_name3, 0 );
lv_obj_set_y( ui_panel1_3_name3, 10 );
lv_obj_set_align( ui_panel1_3_name3, LV_ALIGN_CENTER );
lv_label_set_text(ui_panel1_3_name3,"窗纱关");
lv_obj_set_style_text_color(ui_panel1_3_name3, lv_color_hex(0xF9C584), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_panel1_3_name3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_panel1_3_name3, &ui_font_ooMode, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_panel1_3_polit3 = lv_label_create(ui_panel1_11);
lv_obj_set_width( ui_panel1_3_polit3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_panel1_3_polit3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_panel1_3_polit3, 0 );
lv_obj_set_y( ui_panel1_3_polit3, -36 );
lv_obj_set_align( ui_panel1_3_polit3, LV_ALIGN_CENTER );
lv_label_set_text(ui_panel1_3_polit3,"....");
lv_obj_set_style_text_color(ui_panel1_3_polit3, lv_color_hex(0xCACACA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_panel1_3_polit3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_panel1_3_polit3, &ui_font_ooMode, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_panel1_12 = lv_btn_create(ui_Panel3);
lv_obj_set_width( ui_panel1_12, 100);
lv_obj_set_height( ui_panel1_12, 100);
lv_obj_set_x( ui_panel1_12, 68 );
lv_obj_set_y( ui_panel1_12, 59 );
lv_obj_set_align( ui_panel1_12, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_panel1_12, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_panel1_12, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_panel1_12, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_panel1_12, lv_color_hex(0xC7A881), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_panel1_12, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_panel1_4_name3 = lv_label_create(ui_panel1_12);
lv_obj_set_width( ui_panel1_4_name3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_panel1_4_name3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_panel1_4_name3, 0 );
lv_obj_set_y( ui_panel1_4_name3, 10 );
lv_obj_set_align( ui_panel1_4_name3, LV_ALIGN_CENTER );
lv_label_set_text(ui_panel1_4_name3,"窗帘关");
lv_obj_set_style_text_color(ui_panel1_4_name3, lv_color_hex(0xF9C584), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_panel1_4_name3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_panel1_4_name3, &ui_font_ooMode, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_panel1_4_polit3 = lv_label_create(ui_panel1_12);
lv_obj_set_width( ui_panel1_4_polit3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_panel1_4_polit3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_panel1_4_polit3, 0 );
lv_obj_set_y( ui_panel1_4_polit3, -36 );
lv_obj_set_align( ui_panel1_4_polit3, LV_ALIGN_CENTER );
lv_label_set_text(ui_panel1_4_polit3,"....");
lv_obj_set_style_text_color(ui_panel1_4_polit3, lv_color_hex(0xCACACA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_panel1_4_polit3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_panel1_4_polit3, &ui_font_ooMode, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, -123 );
lv_obj_set_y( ui_Label1, -219 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"5");
lv_obj_set_style_text_font(ui_Label1, &ui_font_MS20B2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label2 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, 120 );
lv_obj_set_y( ui_Label2, -221 );
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"6");
lv_obj_set_style_text_font(ui_Label2, &ui_font_MS20B2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label3 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label3, -118 );
lv_obj_set_y( ui_Label3, 22 );
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"7");
lv_obj_set_style_text_font(ui_Label3, &ui_font_MS20B2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button1 = lv_btn_create(ui_Screen1);
lv_obj_set_width( ui_Button1, 100);
lv_obj_set_height( ui_Button1, 105);
lv_obj_set_x( ui_Button1, 158 );
lv_obj_set_y( ui_Button1, 164 );
lv_obj_set_align( ui_Button1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label4 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label4, 157 );
lv_obj_set_y( ui_Label4, 167 );
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"\\n");

lv_obj_add_event_cb(ui_panel1_1, ui_event_panel1_1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_panel1_2, ui_event_panel1_2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_panel1_3, ui_event_panel1_3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_panel1_4, ui_event_panel1_4, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_panel1_5, ui_event_panel1_5, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_panel1_6, ui_event_panel1_6, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_panel1_7, ui_event_panel1_7, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_panel1_8, ui_event_panel1_8, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_panel1_9, ui_event_panel1_9, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_panel1_10, ui_event_panel1_10, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_panel1_11, ui_event_panel1_11, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_panel1_12, ui_event_panel1_12, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);

}
