// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: buttonsss

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t *ui_Screen1;
lv_obj_t *ui_Panel1;
void ui_event_panel1_1( lv_event_t * e);
lv_obj_t *ui_panel1_1;
lv_obj_t *ui_panel1_1_name2;
lv_obj_t *ui_panel1_1_polit2;
void ui_event_panel1_2( lv_event_t * e);
lv_obj_t *ui_panel1_2;
lv_obj_t *ui_panel1_2_name2;
lv_obj_t *ui_panel1_2_polit2;
void ui_event_panel1_3( lv_event_t * e);
lv_obj_t *ui_panel1_3;
lv_obj_t *ui_panel1_3_name2;
lv_obj_t *ui_panel1_3_polit2;
void ui_event_panel1_4( lv_event_t * e);
lv_obj_t *ui_panel1_4;
lv_obj_t *ui_panel1_4_name2;
lv_obj_t *ui_panel1_4_polit2;
lv_obj_t *ui_Panel2;
void ui_event_panel1_5( lv_event_t * e);
lv_obj_t *ui_panel1_5;
lv_obj_t *ui_panel1_1_name1;
lv_obj_t *ui_panel1_1_polit1;
void ui_event_panel1_6( lv_event_t * e);
lv_obj_t *ui_panel1_6;
lv_obj_t *ui_panel1_2_name1;
lv_obj_t *ui_panel1_2_polit1;
void ui_event_panel1_7( lv_event_t * e);
lv_obj_t *ui_panel1_7;
lv_obj_t *ui_panel1_3_name1;
lv_obj_t *ui_panel1_3_polit1;
void ui_event_panel1_8( lv_event_t * e);
lv_obj_t *ui_panel1_8;
lv_obj_t *ui_panel1_4_name1;
lv_obj_t *ui_panel1_4_polit1;
lv_obj_t *ui_Panel3;
void ui_event_panel1_9( lv_event_t * e);
lv_obj_t *ui_panel1_9;
lv_obj_t *ui_panel1_1_name3;
lv_obj_t *ui_panel1_1_polit3;
void ui_event_panel1_10( lv_event_t * e);
lv_obj_t *ui_panel1_10;
lv_obj_t *ui_panel1_2_name3;
lv_obj_t *ui_panel1_2_polit3;
void ui_event_panel1_11( lv_event_t * e);
lv_obj_t *ui_panel1_11;
lv_obj_t *ui_panel1_3_name3;
lv_obj_t *ui_panel1_3_polit3;
void ui_event_panel1_12( lv_event_t * e);
lv_obj_t *ui_panel1_12;
lv_obj_t *ui_panel1_4_name3;
lv_obj_t *ui_panel1_4_polit3;
lv_obj_t *ui_Label1;
lv_obj_t *ui_Label2;
lv_obj_t *ui_Label3;
void ui_event_Button1( lv_event_t * e);
lv_obj_t *ui_Button1;
lv_obj_t *ui_Label4;
lv_obj_t *ui____initial_actions0;
const lv_img_dsc_t *ui_imgset_1754897865[1] = {&ui_img_906016690};
const lv_img_dsc_t *ui_imgset_497120560[1] = {&ui_img_1538370746};
const lv_img_dsc_t *ui_imgset_114953855[1] = {&ui_img_583893980};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_panel1_1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SHORT_CLICKED) {
      press_panel1_1( e );
}
}
void ui_event_panel1_2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SHORT_CLICKED) {
      press_panel1_2( e );
}
}
void ui_event_panel1_3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SHORT_CLICKED) {
      press_panel1_3( e );
}
}
void ui_event_panel1_4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SHORT_CLICKED) {
      press_panel1_4( e );
}
}
void ui_event_panel1_5( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SHORT_CLICKED) {
      press_panel2_1( e );
}
}
void ui_event_panel1_6( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SHORT_CLICKED) {
      press_panel2_2( e );
}
}
void ui_event_panel1_7( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SHORT_CLICKED) {
      press_panel2_3( e );
}
}
void ui_event_panel1_8( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SHORT_CLICKED) {
      press_panel2_4( e );
}
}
void ui_event_panel1_9( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SHORT_CLICKED) {
      press_panel3_1( e );
}
}
void ui_event_panel1_10( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SHORT_CLICKED) {
      press_panel3_2( e );
}
}
void ui_event_panel1_11( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SHORT_CLICKED) {
      press_panel3_3( e );
}
}
void ui_event_panel1_12( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SHORT_CLICKED) {
      press_panel3_4( e );
}
}
void ui_event_Button1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SHORT_CLICKED) {
      huanhang( e );
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Screen1_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Screen1);
}
