// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: buttonsss

#ifndef _BUTTONSSS_UI_H
#define _BUTTONSSS_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Panel1;
void ui_event_panel1_1( lv_event_t * e);
extern lv_obj_t *ui_panel1_1;
extern lv_obj_t *ui_panel1_1_name2;
extern lv_obj_t *ui_panel1_1_polit2;
void ui_event_panel1_2( lv_event_t * e);
extern lv_obj_t *ui_panel1_2;
extern lv_obj_t *ui_panel1_2_name2;
extern lv_obj_t *ui_panel1_2_polit2;
void ui_event_panel1_3( lv_event_t * e);
extern lv_obj_t *ui_panel1_3;
extern lv_obj_t *ui_panel1_3_name2;
extern lv_obj_t *ui_panel1_3_polit2;
void ui_event_panel1_4( lv_event_t * e);
extern lv_obj_t *ui_panel1_4;
extern lv_obj_t *ui_panel1_4_name2;
extern lv_obj_t *ui_panel1_4_polit2;
extern lv_obj_t *ui_Panel2;
void ui_event_panel1_5( lv_event_t * e);
extern lv_obj_t *ui_panel1_5;
extern lv_obj_t *ui_panel1_1_name1;
extern lv_obj_t *ui_panel1_1_polit1;
void ui_event_panel1_6( lv_event_t * e);
extern lv_obj_t *ui_panel1_6;
extern lv_obj_t *ui_panel1_2_name1;
extern lv_obj_t *ui_panel1_2_polit1;
void ui_event_panel1_7( lv_event_t * e);
extern lv_obj_t *ui_panel1_7;
extern lv_obj_t *ui_panel1_3_name1;
extern lv_obj_t *ui_panel1_3_polit1;
void ui_event_panel1_8( lv_event_t * e);
extern lv_obj_t *ui_panel1_8;
extern lv_obj_t *ui_panel1_4_name1;
extern lv_obj_t *ui_panel1_4_polit1;
extern lv_obj_t *ui_Panel3;
void ui_event_panel1_9( lv_event_t * e);
extern lv_obj_t *ui_panel1_9;
extern lv_obj_t *ui_panel1_1_name3;
extern lv_obj_t *ui_panel1_1_polit3;
void ui_event_panel1_10( lv_event_t * e);
extern lv_obj_t *ui_panel1_10;
extern lv_obj_t *ui_panel1_2_name3;
extern lv_obj_t *ui_panel1_2_polit3;
void ui_event_panel1_11( lv_event_t * e);
extern lv_obj_t *ui_panel1_11;
extern lv_obj_t *ui_panel1_3_name3;
extern lv_obj_t *ui_panel1_3_polit3;
void ui_event_panel1_12( lv_event_t * e);
extern lv_obj_t *ui_panel1_12;
extern lv_obj_t *ui_panel1_4_name3;
extern lv_obj_t *ui_panel1_4_polit3;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_Label3;
void ui_event_Button1( lv_event_t * e);
extern lv_obj_t *ui_Button1;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_906016690);   // assets/icons8-三角形-48.png
LV_IMG_DECLARE( ui_img_1538370746);   // assets/icons8-電源オフボタン-50.png
LV_IMG_DECLARE( ui_img_583893980);   // assets/客房指南2.png


LV_FONT_DECLARE( ui_font_AC_temp_MS70B2);
LV_FONT_DECLARE( ui_font_Downcount_MS12B2);
LV_FONT_DECLARE( ui_font_Guide2_MS18B2);
LV_FONT_DECLARE( ui_font_Guide_MS18B2);
LV_FONT_DECLARE( ui_font_IdleDate_MS30B2);
LV_FONT_DECLARE( ui_font_IdleTime_MS100B2);
LV_FONT_DECLARE( ui_font_Log_MS16B2);
LV_FONT_DECLARE( ui_font_MS14B2);
LV_FONT_DECLARE( ui_font_MS20B2);
LV_FONT_DECLARE( ui_font_Main_MS22B4);
LV_FONT_DECLARE( ui_font_Music_MS18B2);
LV_FONT_DECLARE( ui_font_Music_MS22B2);
LV_FONT_DECLARE( ui_font_Num70);
LV_FONT_DECLARE( ui_font_Vice_MS20B4);
LV_FONT_DECLARE( ui_font_ooMode);
LV_FONT_DECLARE( ui_font_test_MS16B2);
LV_FONT_DECLARE( ui_font_test_MS32B2);


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
