// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: buttonsss

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void press_panel1_1(lv_event_t * e);
void press_panel1_2(lv_event_t * e);
void press_panel1_3(lv_event_t * e);
void press_panel1_4(lv_event_t * e);
void press_panel2_1(lv_event_t * e);
void press_panel2_2(lv_event_t * e);
void press_panel2_3(lv_event_t * e);
void press_panel2_4(lv_event_t * e);
void press_panel3_1(lv_event_t * e);
void press_panel3_2(lv_event_t * e);
void press_panel3_3(lv_event_t * e);
void press_panel3_4(lv_event_t * e);
void huanhang(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
