// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: ertc32

#include "ui.h"
#include "esp_log.h"

#include "config_structs/config_structs.h"
#include "air_conditioner/air_conditioner.h"
#include "panel/panel.h"

#define TAG "ui_event"

void onoff_AC(lv_event_t * e)
{
	// char ac_id_str[2];
	// lv_dropdown_get_selected_str(ui_Screen1Dropdown_curr_AC_ID, ac_id_str, sizeof(ac_id_str));
	// uint8_t ac_id = static_cast<uint8_t>(atoi(ac_id_str));

	// if (ac_map.find(ac_id) != ac_map.end()) {
	// 	auto ac = ac_map[ac_id];
	// 	ac->onoff_AC();

	// 	if (ac->get_running()) {
	// 		lv_label_set_text_fmt(ui_Screen1Label_AC_target_temp, "%d", ac->get_target_temp());
	// 		lv_obj_clear_flag(ui_Screen1Label_AC_target_temp, LV_OBJ_FLAG_HIDDEN);
	// 	} else {
	// 		lv_obj_add_flag(ui_Screen1Label_AC_target_temp, LV_OBJ_FLAG_HIDDEN);
	// 	}
	// } else {
	// 	ESP_LOGE(TAG, "AC %d 不存在", ac_id);
	// }
}

void add_temp(lv_event_t * e)
{
	// char ac_id_str[2];
	// lv_dropdown_get_selected_str(ui_Screen1Dropdown_curr_AC_ID, ac_id_str, sizeof(ac_id_str));
	// uint8_t ac_id = static_cast<uint8_t>(atoi(ac_id_str));

	// if (ac_map.find(ac_id) != ac_map.end()) {
	// 	auto ac = ac_map[ac_id];
	// 	ac->add_temp();
	// 	lv_label_set_text_fmt(ui_Screen1Label_AC_target_temp, "%d", ac->get_target_temp());
	// } else {
	// 	ESP_LOGE(TAG, "AC %d 不存在", ac_id);
	// }
}

void dec_temp(lv_event_t * e)
{
	// char ac_id_str[2];
	// lv_dropdown_get_selected_str(ui_Screen1Dropdown_curr_AC_ID, ac_id_str, sizeof(ac_id_str));
	// uint8_t ac_id = static_cast<uint8_t>(atoi(ac_id_str));

	// if (ac_map.find(ac_id) != ac_map.end()) {
	// 	auto ac = ac_map[ac_id];
	// 	ac->dec_temp();
	// 	lv_label_set_text_fmt(ui_Screen1Label_AC_target_temp, "%d", ac->get_target_temp());
	// } else {
	// 	ESP_LOGE(TAG, "AC %d 不存在", ac_id);
	// }
}

void change_wind_speed(lv_event_t * e)
{
	// char ac_id_str[2];
	// lv_dropdown_get_selected_str(ui_Screen1Dropdown_curr_AC_ID, ac_id_str, sizeof(ac_id_str));
	// uint8_t ac_id = static_cast<uint8_t>(atoi(ac_id_str));

	// if (ac_map.find(ac_id) != ac_map.end()) {
	// 	auto ac = ac_map[ac_id];
	// 	ac->next_wind_speed();
	// 	lv_label_set_text_fmt(ui_Screen1Label_curr_wind_speed, "%s", AC_wind_speed_to_str(ac->get_wind_speed()));
	// } else {
	// 	ESP_LOGE(TAG, "AC %d 不存在", ac_id);
	// }
}


void change_mode(lv_event_t * e)
{
	// char ac_id_str[2];
	// lv_dropdown_get_selected_str(ui_Screen1Dropdown_curr_AC_ID, ac_id_str, sizeof(ac_id_str));
	// uint8_t ac_id = static_cast<uint8_t>(atoi(ac_id_str));

	// if (ac_map.find(ac_id) != ac_map.end()) {
	// 	auto ac = ac_map[ac_id];
	// 	ac->next_mode();
	// 	lv_label_set_text_fmt(ui_Screen1Label_curr_mode, "%s", AC_mode_to_str(ac->get_mode()));
	// } else {
	// 	ESP_LOGE(TAG, "AC %d 不存在", ac_id);
	// }
}

// 面板id:5 | 按钮id:0
void press_panel1_1(lv_event_t * e)
{
	PanelManager::getInstance().getItem(5)->buttons[0].press();
}

void press_panel1_2(lv_event_t * e)
{
	PanelManager::getInstance().getItem(5)->buttons[1].press();
}

void press_panel1_3(lv_event_t * e)
{
	PanelManager::getInstance().getItem(5)->buttons[2].press();
}

void press_panel1_4(lv_event_t * e)
{
	PanelManager::getInstance().getItem(5)->buttons[3].press();
}

void press_panel2_1(lv_event_t * e)
{
	PanelManager::getInstance().getItem(6)->buttons[0].press();
}

void press_panel2_2(lv_event_t * e)
{
	PanelManager::getInstance().getItem(6)->buttons[1].press();
}

void press_panel2_3(lv_event_t * e)
{
	PanelManager::getInstance().getItem(6)->buttons[2].press();
}

void press_panel2_4(lv_event_t * e)
{
	PanelManager::getInstance().getItem(6)->buttons[3].press();
}

void press_panel3_1(lv_event_t * e)
{
	PanelManager::getInstance().getItem(7)->buttons[0].press();
}

void press_panel3_2(lv_event_t * e)
{
	PanelManager::getInstance().getItem(7)->buttons[1].press();
}

void press_panel3_3(lv_event_t * e)
{
	PanelManager::getInstance().getItem(7)->buttons[2].press();
}

void press_panel3_4(lv_event_t * e)
{
	PanelManager::getInstance().getItem(7)->buttons[3].press();
}

void huanhang(lv_event_t * e)
{
	printf("\n\n");
}
